In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.datasets import load_iris

In [13]:
data_array = load_iris()
data_array

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [14]:
data = pd.read_csv('iris.data.csv')

In [63]:

def euclidean_distance(x1, x2,):
    """
    Computes Euclidean distance between two vectors
    """

    return np.sqrt(np.sum((x1 - x2) ** 2))
    

In [178]:
x = data.iloc[:150,:-1].values
x = np.array(x)

In [179]:
a,b= x[[1,2]]


In [180]:
a


array([4.7, 3.2, 1.3, 0.2])

In [181]:
b

array([4.6, 3.1, 1.5, 0.2])

In [231]:
n,m = data.shape
# k = n*m
n,m

(149, 5)

In [183]:
euclidean_distance(a,b)

0.24494897427831802

In [189]:
# random_index = np.random.choice(len(x),n)
# centroids = x[random_index]

random_index = np.random.choice(len(x),n)
cg0,cg1,cg2 = x[random_index],x[random_index],x[random_index]


In [204]:
distance0 = []
distance1 = []
distance2 = []

for i in range(n):
    dist0 = euclidean_distance(x[i], cg0[0])
    distance0.append(dist0)

for i in range(n):
    dist = euclidean_distance(x[i], cg1[1])
    distance1.append(dist)
    
for i in range(n):
    dist0 = euclidean_distance(x[i], cg2[2])
    distance2.append(dist0)
 # dist1 = euclidean_distance(x[i], centroids[1])
 #    dist2 = euclidean_distance(x[i], centroids[2])
 #    distance1.append(dist1)
 #    distance1.append(dist2)

In [205]:
distance0[0],distance1[0],distance2[0]

(0.9848857801796101, 0.22360679774997896, 0.4582575694955841)

In [206]:
max(distance0[0],distance1[0],distance2[0])

0.9848857801796101

In [207]:
labels = []
for i in range(n):
    labels.append(int((min(distance0[i],distance1[i],distance2[i]))))

In [208]:
labels[0]

0

In [209]:
cl0,cl1,cl2 = [],[],[]

In [210]:
label = np.array(labels)

In [211]:
cl0 = x[np.where(label == 0)[0]]

# clusterindex = np.where(label == 0)[0]
# cl0 = clusterindex

In [212]:
cl1 = x[np.where(label == 1)[0]]

In [213]:
cl2 = x[np.where(label == 2)[0]]

In [214]:
cl0

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3

In [215]:
cl1

array([[5.8, 4. , 1.2, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [5.1, 2.5, 3. , 1.1]])

In [216]:
cl2

array([[5.5, 2.3, 4. , 1.3],
       [5.7, 2.8, 4.5, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.6, 2.5, 3.9, 1.1],
       [6.1, 2.8, 4. , 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [5.4, 3. , 4.5, 1.5],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.8, 4.1, 1.3]])

In [219]:
cg0 = np.mean(cl0,axis=0)
cg0

array([4.9875    , 3.40416667, 1.47083333, 0.24583333])

In [221]:
cg1 = np.mean(cl0,axis=0)
cg1

array([4.9875    , 3.40416667, 1.47083333, 0.24583333])

In [222]:
cg2 = np.mean(cl0,axis=0)
cg2

array([4.9875    , 3.40416667, 1.47083333, 0.24583333])

In [232]:
for k in range(10):
    cl0_k, cl1_k, cl2 = []
    print("iteration:",k)
    distance0 = []
    distance1 = []
    distance2 = []
    
    for i in range(n):
        dist0 = euclidean_distance(x[i], cg0[0])
        distance0.append(dist0)
    
    for i in range(n):
        dist = euclidean_distance(x[i], cg1[1])
        distance1.append(dist)
        
    for i in range(n):
        dist0 = euclidean_distance(x[i], cg2[2])
        distance2.append(dist0)
    
    labels = []
    for i in range(n):
        labels.append(int((min(distance0[i],distance1[i],distance2[i]))))
    
    label = np.array(labels)
    print(label)
    
    cl0 = x[np.where(label == 0)[0]]
    cl1 = x[np.where(label == 1)[0]]
    cl2 = x[np.where(label == 2)[0]]

iteration: 0
[3 3 3 4 4 3 4 3 4 4 3 3 3 4 4 4 4 4 4 4 3 4 3 3 4 3 4 4 3 3 4 4 4 4 4 4 4
 3 4 4 3 3 3 3 3 4 3 4 4 4 3 4 3 3 3 3 3 4 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 4 4 3 3 3 3 3 3 2 3 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 3 4 2 4 4 3 3 3
 3 3 3 3 4 4 4 3 3 3 4 3 3 4 3 3 3 4 4 4 3 3 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3
 3]
iteration: 1


IndexError: index 0 is out of bounds for axis 0 with size 0